// react-app/src/components/CurrencyRate/CurrencyRate.tsx
import React, { useState, useEffect } from "react";
import { FormattedCurrencyData } from "src/types/currency.interface";
import { getCurrencyResult } from "@services/currency";
import "./currency-rate.scss";

export function CurrencyRateComponent() {
  const [currencyResponse, setCurrencyResponse] =
    useState<FormattedCurrencyData | null>(null);
  const [selectedCurrency, setSelectedCurrency] = useState("CNY");
  const [currencyRate, setCurrencyRate] = useState(1);

  useEffect(() => {
    fetchCurrencyData();
  }, []);

  async function fetchCurrencyData() {
    const response = await getCurrencyResult();
    if (response) {
      setCurrencyResponse(response);
      const rate = getCurrencyRate(
        response.defaultExchangeCode,
        response.conversionRates
      );
      setCurrencyRate(rate);
    }
  }

  function onSelectCurrency(event: React.ChangeEvent<HTMLSelectElement>): void {
    const selectedValue = event.target.value;
    setSelectedCurrency(selectedValue);

    if (currencyResponse) {
      const rate = getCurrencyRate(
        selectedValue,
        currencyResponse.conversionRates
      );
      setCurrencyRate(rate);
    }
  }

  function getCurrencyRate(
    currency: string,
    conversionRates: {
      [currencyCode: string]: number;
    }
  ): number {
    const currencyRate = conversionRates[currency] ?? 0;
    return Math.round(currencyRate * 100) / 100;
  }

  if (!currencyResponse) {
    return null;
  }

  return (
    <div className="app-currency-component">
      <div className="base-currency">1 USD exchanges</div>

      <div className="exchange-currency">
        {`${currencyRate} ${selectedCurrency}`}
      </div>

      <div className="update-date">
        {currencyResponse?.lastUpdateTime} update from {""}
        <a href="https://www.exchangerate-api.com/">ExchangeRate-API</a>
      </div>

      <div className="currency-selection">
        <div className="select-currency-rate">{currencyRate}</div>

        <select
          value={selectedCurrency}
          onChange={onSelectCurrency}
          className="select-currency"
        >
          {Object.entries(currencyResponse.conversionRates).map(
            ([currency, rate]) => (
              <option key={`currency_${currency}`} value={selectedCurrency}>
                {currency}
              </option>
            )
          )}
        </select>
      </div>
    </div>
  );
}

// angular-app/src/app/features/currency-rate/currency-rate.component.ts
import { Component, OnInit } from '@angular/core';
import { CurrencyService } from '@core/currency.service';
import { FormattedCurrencyData } from '@core/currency.interface';

@Component({
  selector: 'app-currency-rate',
  templateUrl: './currency-rate.component.html',
  styleUrl: './currency-rate.component.scss',
})
export class CurrencyRateComponent implements OnInit {
  public currencyResponse: FormattedCurrencyData | null = null;
  public selectedCurrency = 'CNY';
  public calculateCurrencyRate = 1;

  public constructor(protected currencyService: CurrencyService) {}

  public ngOnInit(): void {
    this.init();
  }

  public async init(): Promise<void> {
    this.currencyResponse = await this.currencyService.getCurrencyResult();
    if (this.currencyResponse) {
      this.calculateCurrencyRate = this.getCurrencyRate(
        this.currencyResponse?.defaultExchangeCode
      );
    }
  }

  public onSelectCurrency(event: Event): void {
    const selectElement = event.target as HTMLSelectElement;
    this.selectedCurrency = selectElement.value;
    this.calculateCurrencyRate = this.getCurrencyRate(this.selectedCurrency);
  }

  public getCurrencyRate(currency: string): number {
    const currencyRate = this.currencyResponse?.conversionRates[currency] ?? 0;
    return Math.round(currencyRate * 100) / 100;
  }
}

<div class="app-currency-component">
  <div class="base-currency">1 USD exchanges</div>

  <div class="exchange-currency">
    {{ this.calculateCurrencyRate }} {{ this.selectedCurrency }}
  </div>

  <div class="update-date">
    {{ this.currencyResponse?.lastUpdateTime }} update ·
    <a href="https://www.exchangerate-api.com/">ExchangeRate-API</a>
  </div>

  <div class="currency-selection">
    <div class="select-currency-rate">{{ this.calculateCurrencyRate }}</div>

    <select
      [(ngModel)]="selectedCurrency"
      (change)="onSelectCurrency($event)"
      class="select-currency"
    >
      <option
        *ngFor="let currency of this.currencyResponse?.currencyOptions"
        [value]="currency"
      >
        {{ currency }}
      </option>
    </select>
  </div>
</div>
